### ISSUE TITLE
есть ли в данной библиотеке парсер грамматики составляющих?

### ISSUE THREAD

**Issue by edgar2597** [buriy/spacy-ru#13]

**Comment by buriy** [comment]
В spacy можно самому такой классификатор написать при желании, но из коробки ни для одного языка такого классификатора нет. Даже для англ языка используется более полезная на практике грамматика зависимостей (точнее, её обобщение, поддерживающее непроективные связи).

Слова для поиска: "spacy constituency grammar"

Скажем, кто-то написал https://github.com/nikitakit/self-attentive-parser , который умеет constituency parsing для 11 языков, но русского там нет, и даже для английского там очень маленький по современным меркам датасет WSJ.
