### ISSUE TITLE
Обновить spacy до последней версии

### ISSUE THREAD

**Issue by rominf** [buriy/spacy-ru#6]
Следую инструкции, но использую последнюю (`2.1.3`) версию spacy (использую возможности, появившиеся в `2.1`). При `spacy.load` получаю длинный stacktrace, заканчивающийся на:
```
error: bad escape \p at position 275
```

Обновите, пожалуйста, spacy до последней версии.

**Comment by buriy** [comment]
Для 2.1 нужно переделывать некоторые места, да.
Планируется новый релиз (где-то в мае, видимо).

**Comment by buriy** [comment]
Если хочешь помочь/ускорить -- могу рассказать как именно и чем, пиши в личку.

**Comment by amelkikh** [comment]
> Для 2.1 нужно переделывать некоторые места, да.
> Планируется новый релиз (где-то в мае, видимо).

Привет. Май уже прошел, июнь на исходе тоже. Будет релиз?

**Comment by buriy** [comment]
@amelkikh 
Привет.
Мне пока никто не помогает, времени менеджить людей самому у меня тоже пока нет.
На следующей неделе я подготовлю первую альфу, там посмотрим уже более предметно на сроки.
Где-то задержка на два месяца получается по планам, то есть в июле будет релиз.
Там вообще ничего сложного (после того, как разберёшься, конечно), просто у меня это не первым приоритетом шло.

**Comment by true1337** [comment]
@buriy я хочу помочь развивать, тк повязан с Rasa

**Comment by buriy** [comment]
@true1337 
Ну, на днях будет альфа-версия, включающая морфо, синтаксис. Потом ещё через пару дней версия с базовым NER.
Дальнейшие планы по NER описаны здесь:
https://github.com/buriy/spacy-ru/issues/9
Планы по Syntax: датасет есть лишь один, ничего не меняется.
Планы по морфологии: я сделаю альфа-версию, потом подумаю, что можно сделать. Есть более крупные датасеты, чем тот, что был использован для морфо-синтаксиса, и всё это подробно было расписано здесь: https://habr.com/ru/company/sberbank/blog/418701/

**Comment by buriy** [comment]
@rominf @amelkikh @true1337 Я сделал альфа-версию:
https://github.com/buriy/spacy-ru/tree/v2.1
Она умеет то же, что и версия для 2.0, т.е. tagger & parser.
У меня examples работают, но может найдёте то, что не работает.
А я сосредоточусь на более точном tagger и на NER.
Желающие мне помочь в ближайшие две-три недели -- пишите мне в телеграм t.me/yuri_baburov , в skype:yuri.baburov или на ODS в личку юзер buriy .

**Comment by rominf** [comment]
@buriy Можешь обновить Readme в той ветке?

**Comment by buriy** [comment]
@rominf обновил: https://github.com/buriy/spacy-ru/blob/v2.1/README.md

**Comment by buriy** [comment]
Текущая версия 2.3, закрываю.
