### ISSUE TITLE
Couldn't create Lemmatizer 

### ISSUE THREAD

**Issue by ardakshalkar** [buriy/spacy-ru#8]
ru2.lemmatizer.DEBUG = 1
---> nlp_r2=pipe_add(ru2.Russian2())
print("R2 pipeline: {}".format(nlp_r2.pipe_names))
parse(nlp_r2, text)

The code above showed error:
/home/ardak/Code/Spacy-ru/ru2/lemmatizer.py in __init__(self)
     18 
     19     def __init__(self):
---> 20         super(RussianLemmatizer, self).__init__()
     21         try:
     22             from pymorphy2 import MorphAnalyzer

TypeError: super(type, obj): obj must be an instance or subtype of type

What is an error?

**Comment by buriy** [comment]
Please check you're using spacy 2.0.12 for this version.
